# Generated by Django 2.2.4 on 2019-11-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log_Standing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.IntegerField(max_length=200)),
                ('Team', models.CharField(max_length=200)),
                ('GP', models.IntegerField(max_length=200)),
                ('W', models.IntegerField(max_length=200)),
                ('D', models.IntegerField(max_length=200)),
                ('L', models.IntegerField(max_length=200)),
                ('GF', models.IntegerField(max_length=200)),
                ('GA', models.IntegerField(max_length=200)),
                ('GD', models.IntegerField(max_length=200)),
                ('PTS', models.IntegerField(max_length=200)),
                ('Club', models.CharField(max_length=200)),
            ],
        ),
    ]
