# Generated by Django 2.2.4 on 2019-11-11 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_standing',
            name='Position',
        ),
    ]
