# Generated by Django 2.2.4 on 2019-11-11 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_remove_log_standing_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_standing',
            old_name='GP',
            new_name='Games',
        ),
    ]
