# Generated by Django 2.2.4 on 2019-11-11 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_auto_20191112_0050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log_standing',
            old_name='Games',
            new_name='GP',
        ),
    ]
