# Generated by Django 2.2.4 on 2019-11-12 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0004_auto_20191112_0105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='log_standing',
            name='Club',
        ),
    ]
