# Generated by Django 2.2.4 on 2019-11-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0005_remove_log_standing_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='log_standing',
            name='Position',
            field=models.IntegerField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
