# Generated by Django 2.2.4 on 2019-11-12 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0006_log_standing_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fixtures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(max_length=200)),
                ('Time', models.TimeField(max_length=200)),
                ('TeamA', models.CharField(max_length=200)),
                ('VS', models.CharField(max_length=200)),
                ('TeamB', models.CharField(max_length=200)),
                ('Stadium', models.CharField(max_length=200)),
            ],
        ),
    ]
