# Generated by Django 2.2.4 on 2019-11-12 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0010_auto_20191112_2349'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fixtures',
            old_name='TeamA',
            new_name='Away',
        ),
        migrations.RenameField(
            model_name='fixtures',
            old_name='TeamB',
            new_name='Home',
        ),
    ]
