# Generated by Django 2.2.4 on 2019-11-13 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0014_auto_20191113_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='first_name',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
    ]
