# Generated by Django 2.2.4 on 2019-11-14 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0015_auto_20191114_0054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='results',
            name='Score',
            field=models.IntegerField(max_length=200),
        ),
    ]
