# Generated by Django 2.2.4 on 2019-11-14 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0017_auto_20191114_0213'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Team', models.CharField(max_length=200)),
                ('Name', models.CharField(max_length=200)),
                ('Surname', models.CharField(max_length=200)),
                ('Student_Number', models.CharField(max_length=200)),
                ('Institution', models.CharField(max_length=200)),
            ],
        ),
    ]
