# Generated by Django 2.2.4 on 2019-11-14 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0018_playersname'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixtures',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
