# Generated by Django 2.2.4 on 2019-11-14 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0019_auto_20191114_0337'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PlayersName',
            new_name='PlayersDetails',
        ),
    ]
